### ISSUE TITLE
No registered RP4VMs clusters

### ISSUE THREAD

**Issue by gtaraujo68** [IdanKen/Dell-EMC-RecoverPoint4VMs#1]
Hello
I am trying to use your script to automate RP4VM but I am having a problem

PS Z:\trabalho\Comum\RP4VM> .\RP4VMs-Protect.ps1 -vc VC10 -credentials $credentials -esxcluster VXRAIL-CLUSTER-PRD -pluginserver HCRPA00 -tag DRTAG
-> Connecting to vCenter:

Name                           Port  User                          
----                           ----  ----                          
VC10                      443   company\gtaraujo68

Invoke-RestMethod : Não é possível localizar um parâmetro que coincida com o nome de parâmetro 'SkipCertificateCheck'.
No Z:\trabalho\Comum\RP4VM\RP4VMs-Protect.ps1:95 caractere:57
+ ... Invoke-RestMethod -Method GET -uri $uri -SkipCertificateCheck -Header ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-RestMethod], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
No registered RP4VMs clusters, configure through Deployer or register vCenter through the API

Could you please let me know if this problem could be solved? 
Thanks in advance!

Guilherme

**Comment by IdanKen** [comment]
Hi Guilherme,
Just to make sure, have you registered the plugin server after deploying one or more RPVM clusters ?

Regards,
Idan

**Comment by gtaraujo68** [comment]
we have a plugin in VCenter
do you have a command to check if it is ok or not?

**Comment by IdanKen** [comment]
Either through the plugin (System -> Administration -> vRPA clusters) or through the following call:
https://{{pluginServer}}/api/v1/rp-systems

**Comment by gtaraujo68** [comment]
in system there are "vCenter Servers / ESC Clusters / Datastores/ Orchestration / Plugin Server / Licenses"
In Plugin Server option our 2 vRPA cluster are present

**Comment by IdanKen** [comment]
Config issue
