### ISSUE TITLE
timeout during cluster deployment

### ISSUE THREAD

**Issue by HCIdiver** [IdanKen/Dell-EMC-RecoverPoint4VMs#3]
Hey Idan.
I was depoying on another lab system... and ran into a weitd issue where the deployed rp4vm nodes arent accepting the password...  im going to redeploy with your latest and see if it fixes it. 

line 235 mentions dns/ntp
line 627 i think is network related... maybe the new lab vc is setup oddly...

Completed successfully
 ---> OVA deployment completed successfully
-> Checking connectivity to vRPAs
---> vRPA Mgmt IP 10.204.8.125 is reachable
---> vRPA Mgmt IP 10.204.8.126 is reachable
---> All vRPAs are reachable
->The call POST https://10.204.8.125/deployer/rest/5_2/user/sessions failed with exception:401 Client Error:  for url: https://10.204.8.125/deployer/rest/5_2/user/sessions
Traceback (most recent call last):
  File "rp4vms_deploy_v2.py", line 692, in <module>
    main()
  File "rp4vms_deploy_v2.py", line 627, in main
    token = init_rest_call("POST", loginUri, loginPayload, loginPayload)
  File "rp4vms_deploy_v2.py", line 235, in init_rest_call
    raise Exception('\033[91m\033[1m->Failed to query {}, code: {}, body: {}'.format(uri, response.status_code, response.text))
Exception: ->Failed to query https://10.204.8.125/deployer/rest/5_2/user/sessions, code: 401, body: "Authentication failed, invalid username or password"
[root@linuxhelper Downloads]#

**Comment by HCIdiver** [comment]
tried latest version...

---> All vRPAs are reachable
-> Running deployment pre-validation checks
---> Transaction LOCAL_1 RUNNING 0%
---> Warnings detected in pre-installation validation
Several issues were found
-> Timezone detected: Europe/London
-> Searching for available vRPAs
---> Transaction LOCAL_2 RUNNING 0%
---> Transaction LOCAL_2 RUNNING 50%
-> DS for Repository Volume detected
-> Mgmt Network detected
-> Data Network detected
-> Building deployment configuration
-> Deploying RP4VMs cluster
---> Transaction DEPLOY_3 RUNNING 0%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 52%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 53%
---> Transaction DEPLOY_3 RUNNING 84%
---> Transaction DEPLOY_3 RUNNING 84%
---> Transaction DEPLOY_3 RUNNING 84%
---> Transaction DEPLOY_3 RUNNING 84%
->Error Connecting to https://10.204.8.125/deployer/rest/5_2/user/sessions: HTTPSConnectionPool(host='10.204.8.125', port=443): Max retries exceeded with url: /deployer/rest/5_2/user/sessions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f058c9b4a58>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by IdanKen** [comment]
Statistic timeout while waiting to renew creds during cluster deployment. Will look into refactoring this monitoring aspect soon.

**Comment by HCIdiver** [comment]
chat next week if free. i think it might be a dns/ntp issue my side.

**Comment by IdanKen** [comment]
Fixed in later versions of the solution
