### ISSUE TITLE
How to use protectvm.py

### ISSUE THREAD

**Issue by Borg99** [IdanKen/Dell-EMC-RecoverPoint4VMs#4]
Hey Idan.
I want to learn how to use protectvm.py

For example:
protectvm.py -s XXX.XXX.XXX.XXX

Could you give me an example

Or give me some explanation
Protectvm.py - h I didn't understand

Thank

**Comment by IdanKen** [comment]
Check out the new revision of the script, run with -h to see some quick examples, and let me know if you need anything else.
